#!/bin/bash

# Install Nginx
sudo apt update
sudo apt install nginx

# Check Nginx status
sudo systemctl status nginx

# Check Nginx configuration file for errors
sudo nginx -t

# Open port 80 on firewall
sudo ufw allow 80/tcp

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx service
sudo systemctl restart nginx

